/**
 * Centralized Branding Configuration
 *
 * All UI branding is sourced from here. White-label clients override these
 * values via environment variables. If no env var is set, the default
 * "Inzeedo ERP" branding is used as a safe fallback.
 *
 * Usage:
 *   import { BRAND } from "@/lib/branding";
 *   <h1>{BRAND.APP_NAME}</h1>
 */

export const BRAND = {
  // ─── Identity ──────────────────────────────────────────────────────────────
  APP_NAME: process.env.NEXT_PUBLIC_APP_NAME || "Inzeedo ERP",
  SHORT_NAME: process.env.NEXT_PUBLIC_APP_SHORT_NAME || "Inzeedo",
  LOGO: process.env.NEXT_PUBLIC_APP_LOGO || "/images/inzeedo-logo-dark.png",
  LOGO_LIGHT: process.env.NEXT_PUBLIC_APP_LOGO_LIGHT || "/images/inzeedo-logo-light.png",
  FAVICON: process.env.NEXT_PUBLIC_APP_FAVICON || "/favicon.ico",

  // ─── Theming ───────────────────────────────────────────────────────────────
  PRIMARY_COLOR: process.env.NEXT_PUBLIC_PRIMARY_COLOR || "#10b981", // Inzeedo Emerald

  // ─── Contact & Support ─────────────────────────────────────────────────────
  SUPPORT_EMAIL: process.env.NEXT_PUBLIC_SUPPORT_EMAIL || "support@inzeedo.com",
  SUPPORT_PHONE: process.env.NEXT_PUBLIC_SUPPORT_PHONE || "+94-777-000000",
  WEBSITE: process.env.NEXT_PUBLIC_COMPANY_WEBSITE || "https://inzeedo.com",

  // ─── Feature Flags ─────────────────────────────────────────────────────────
  // White-label mode hides system-level branding (footer credit, about page).
  IS_WHITE_LABEL: process.env.NEXT_PUBLIC_IS_WHITE_LABEL === "true",

  // Subscription and system health pages (hidden by super-admins for clients).
  SHOW_SUBSCRIPTION: process.env.NEXT_PUBLIC_SHOW_SUBSCRIPTION !== "false",
  SHOW_SYSTEM_HEALTH: process.env.NEXT_PUBLIC_SHOW_SYSTEM_HEALTH !== "false",

  // ─── Derived Helpers ───────────────────────────────────────────────────────
  /** Copyright line e.g. "© 2026 Inzeedo. All rights reserved." */
  COPYRIGHT: `© ${new Date().getFullYear()} ${process.env.NEXT_PUBLIC_APP_SHORT_NAME || "Inzeedo"}. All rights reserved.`,

  /** Footer credit line – hidden in white-label mode */
  CREDIT_LINE: process.env.NEXT_PUBLIC_IS_WHITE_LABEL === "true"
    ? ""
    : "A next-generation enterprise solution, proudly developed and maintained by Inzeedo.",

  /** Short receipt footer e.g. "ERP SYSTEM FROM INZEEDO" */
  RECEIPT_FOOTER: process.env.NEXT_PUBLIC_IS_WHITE_LABEL === "true"
    ? (process.env.NEXT_PUBLIC_APP_SHORT_NAME || "").toUpperCase()
    : "ERP SYSTEM FROM INZEEDO",

  /** Receipt website/contact line */
  RECEIPT_CONTACT: process.env.NEXT_PUBLIC_IS_WHITE_LABEL === "true"
    ? (process.env.NEXT_PUBLIC_SUPPORT_PHONE || "")
    : "© 2026 INZEEDO.LK | +94785706441",

  /** Used in print report footers */
  REPORT_GENERATED_BY: `Generated by ${process.env.NEXT_PUBLIC_APP_NAME || "Inzeedo ERP"} System`,

  /** POS terminal display welcome message */
  POS_DISPLAY_NAME: (process.env.NEXT_PUBLIC_APP_SHORT_NAME || "INZEEDO POS").toUpperCase(),

  /** Used in document.title */
  PAGE_TITLE_SUFFIX: process.env.NEXT_PUBLIC_PAGE_TITLE_SUFFIX || process.env.NEXT_PUBLIC_APP_SHORT_NAME || "Inzeedo POS",
};
